---
- name: Install SELinux files
  dnf:
    name: libselinux-python
    state: present
    disablerepo: fedora-modular-server,fedora-modular-server-updates-testing

- name: Create system profile directory
  file:
    path: /etc/dnf/modules.defaults.d
    state: directory
    mode: 0755

- name: Download latest F27 system profile
  get_url:
    url: https://raw.githubusercontent.com/container-images/boltron-27/master/base-27.defaults
    dest: /etc/dnf/modules.defaults.d/
    mode: 0644
    force: yes

- name: Add the Modular Server repo to install modular-aware DNF
  yum_repository:
    name: fedora-modular-server
    description: Fedora Modular Server
    mirrorlist: https://mirrors.fedoraproject.org/metalink?repo=modular-fedora-server-f$releasever&arch=$basearch
    gpgcheck: no
    priority: 90
    enabled: no

- name: Install DNF from the Modular Server Repo
  dnf:
    name: dnf
    state: latest
    disablerepo: fedora,updates
    enablerepo: fedora-modular-server

- name: Enable prototype module repository
  yum_repository:
    name: test-modules
    description: Test repo for modules
    baseurl: https://asamalik.fedorapeople.org/modularity-hybrid-demo/repos/modules/
    priority: 90
    gpgcheck: no
    enabled: yes
