---
- name: Install SELinux files
  dnf:
    name: libselinux-python
    state: present
    disablerepo: fedora-modular,fedora-dnf-copr

- name: Create system profile directory
  file:
    path: /etc/dnf/modules.defaults.d
    state: directory
    mode: 0755

- name: Drop in Review Board system profile
  copy:
    src: files/reviewboard.defaults
    dest: /etc/dnf/modules.defaults.d/
    mode: 0644
    force: yes

- name: Add the Modular DNF COPR repo to install modular-aware DNF
  yum_repository:
    name: fedora-dnf-copr
    description: Fedora Modular DNF
    baseurl: https://copr-be.cloud.fedoraproject.org/results/mhatina/dnf-modularity-stable/fedora-rawhide-$basearch/
    gpgcheck: no
    priority: 90
    enabled: yes

- name: Install DNF from COPR
  command: dnf -y distro-sync *dnf*

- name: Enable prototype module repository
  yum_repository:
    name: fedora-modular
    description: Test repo for modules
    baseurl: https://sgallagh.fedorapeople.org/repo/devconf2017/x86_64/os/
    priority: 90
    gpgcheck: no
    enabled: yes
